### ISSUE TITLE
能否回归本质，使用|完成对于一个8位寄存器的赋值操作。

### ISSUE THREAD

**Issue by MALossov** [kifuan/helang#102]
在单片机控制当中，|运算一般和宏定义相结合完成对于某个功能寄存器的赋值操作，而Great的HeLang应该也能完成这些。所以能否回归|的本质，增加|运算对于寄存器的控制。

**Comment by kifuan** [comment]
需要demo喵，需要demo谢谢喵

**Comment by MALossov** [comment]
> 需要demo喵，需要demo谢谢喵

就比如MSP430F5529中设置时钟源使用的语句：
UCSCTL4 = UCSCTL4&(~(SELS_7|SELM_7))|SELS_2|SELM_2; //将SMCLK和MCLK配置为REFOCLK
能否用Helang进行实现。
（编不下去了就这吧）

**Comment by kifuan** [comment]
你的意思是正常的位运算操作符吗？
但是我的同学不会用，他说

> 非常坏语法，不好！恨来自瓷器

**Comment by MALossov** [comment]
> 



> 你的意思是正常的位运算操作符吗？ 但是我的同学不会用，他说
> 
> > 非常坏语法，不好！恨来自瓷器

> 没有单片机！抽象非常多硬件！非常伟大语言！爱来自瓷器。

那我有空去看看pico的micropython能不能跑。
