### ISSUE TITLE
[Feature request] 建议加入中美混血、美国公民等属性的支持

### ISSUE THREAD

**Issue by huntzhan** [kifuan/helang#106]
考虑彻底加入何谷丁宇宙

**Comment by kifuan** [comment]
**Cyber Spaces**, where the **Saint He** lives in, **DOES NOT** belong to any countries on the earth.

**Comment by huntzhan** [comment]
> **Cyber Spaces**, where the **Saint He** lives in, **DOES NOT** belong to any countries on the earth.

**Cyber Spaces** connects **EVERYTHING**, just like **5G**!

**Comment by kifuan** [comment]
But how these property should be supported?

**Comment by huntzhan** [comment]
建议可以在这里加一个关键词 `testAmericanCitizenship`，实际的作用是检查 IP 是否在美国境内（更高阶的功能可能涉及检测是否在美国的殖民地比如日本台湾等地）：

https://github.com/kifuan/helang/blob/a6a7c9ad9c1894868b7a675729f04a1ac9d0e65a/helang/tokens.py#L65

**Comment by JunweiSUN** [comment]
基督教有唯一上帝，赛博宇宙我也只认唯一真神何圣捏

**Comment by kifuan** [comment]
加上了，只不过叫做测试你是否处在 **Cyber Spaces** 😋
