### ISSUE TITLE
一坨史这个何语言

### ISSUE THREAD

**Issue by LavaCxx** [kifuan/helang#120]

**Comment by kifuan** [comment]
你怎么敢骂何圣😠👊

**Comment by xieyuheng** [comment]
就是就是

**Comment by ningningNO1** [comment]
不许你这么说小何
![1D011BD1](https://user-images.githubusercontent.com/73210986/185299206-a6687cfe-b7b6-4e5d-b012-9addf4116bea.png)

**Comment by kifuan** [comment]
非常差 `issue`，气愤！恨来自**Cyber Spaces**。
