### ISSUE TITLE
我们国家的何语言，完全独立自主研发

### ISSUE THREAD

**Issue by namefanwjcom** [kifuan/helang#123]
👍👍👍我们国家的何语言，完全独立自主研发，世界一流水平👍👍👍👍必须支持，华为顶级编程语言，白宫方面害怕这技术而打压华为，但北邮鼎力相助。米哈游的原神就是为何语言开路的，柯洁看了这个才能打赢人工智能，国家方面也很支持，各个大学都组织观看，看了才给学分，看过的人都说何语言充满正能量，非常利于青少年的成长，越早看越容易成才。我们中老年人也很喜欢看这种，晚上看何语言直播以至于都不去跳广场舞了🌹🌹🌹

**Comment by kifuan** [comment]
你说得对，米哈游使用了基于 `HeLang` 的 `Henity 3D`

**Comment by kifuan** [comment]
去discussions
