### ISSUE TITLE
我宣布 helang正式取代php成为世界上最好的编程语言!!!

### ISSUE THREAD

**Issue by Zong0117** [kifuan/helang#129]
关注嘉然 顿顿解馋
![9356ac54-efc0-4975-b98f-89417f727788](https://user-images.githubusercontent.com/64644244/185302560-40f0aa5a-65a4-4eba-9c0c-08e61e37fe0c.jpg)

**Comment by kifuan** [comment]
夹心糖真的是

**Comment by SakuraPuare** [comment]
图穷匕见了是吧，关注[永雏塔菲](https://space.bilibili.com/1265680561)喵，关注[永雏塔菲](https://space.bilibili.com/1265680561)谢谢喵。

**Comment by kifuan** [comment]
去discussions
