### ISSUE TITLE
花了多少小时输出一个hello word？

### ISSUE THREAD

**Issue by haoruilee** [kifuan/helang#13]
感觉不如何同学...代码能力

**Comment by kifuan** [comment]
我就没打算写Hello World，直接5G测速。

**Comment by haoruilee** [comment]
> 我就没打算写Hello World，直接5G测速。
不觉得很觉得吗？我觉得这实在是太觉得了，作为一个理科生，符合我对觉得的所有觉得！

**Comment by kifuan** [comment]
太酷了，现在支持Hello, world了
