### ISSUE TITLE
JetBrains 连夜推出新的 idea 

### ISSUE THREAD

**Issue by Sayyiku** [kifuan/helang#130]
好好好，你做的好啊！

**Comment by kifuan** [comment]
Hetellij Idea

**Comment by hellodk34** [comment]
我猜你是想说 ide 却多打了个 a 🤣

**Comment by MomokkoW** [comment]
> 我猜你是想说 ide 却多打了个 a 🤣

其实说是JetBrains IntelliJ IDEA也没问题（所有的JetBrains IDE基本上都是based on IntelliJ IDEA

**Comment by kifuan** [comment]
去discussions
