### ISSUE TITLE
只举办一个人是吧

### ISSUE THREAD

**Issue by SekiBetu** [kifuan/helang#141]
已标记，加入棺材铺仇恨教育😡😡😡

**Comment by kifuan** [comment]
罕见还不让骂了是吧😡😡😡😡😡😡😡😡

**Comment by SekiBetu** [comment]
> 罕见还不让骂了是吧😡😡😡😡😡😡😡😡

就好罕见这一口！就好罕见这一口！不准你骂！不准你骂！(´；ω；`)呜呜呜

**Comment by kifuan** [comment]
你们棺材铺就这点骨气吗🤣

**Comment by SAFEluren** [comment]
棺材铺快|

**Comment by Vucius** [comment]
![0FFL~0QJFMQ}QO B`Y$PPV](https://user-images.githubusercontent.com/81354644/185521543-21a9c44a-dedf-4dfd-bd70-a4f36def6c13.jpg)

**Comment by kifuan** [comment]
去discussions
