### ISSUE TITLE
C++ 语言表示抗议！

### ISSUE THREAD

**Issue by Smalldy** [kifuan/helang#142]
![图片](https://user-images.githubusercontent.com/14820063/185350570-b145daf6-ce00-4b97-a4c0-d4bd3b23154d.png)

**Comment by kifuan** [comment]
很喜欢Linus的一句话：

> It really is a crap language

**Comment by xiaokang00010** [comment]
写个 `class` 名字为 `u8` 然后重载这些运算符不就行了...

**Comment by kifuan** [comment]
然而你并不能用 `1 | 2  | 3` 创建一个类似向量的 `u8` 😘

**Comment by Smalldy** [comment]
> 写个 class 名字为 u8 然后重载这些运算符不就行了...

talk is cheap, show me your code !

**Comment by kifuan** [comment]
> > 写个 class 名字为 u8 然后重载这些运算符不就行了...
> 
> talk is cheap, show me your code !

我在睿站发的视频不是有一个C++的吗

**Comment by Smalldy** [comment]
> 我在睿站发的视频不是有一个C++的吗

啊 我不知道 整一个我瞅瞅

**Comment by kifuan** [comment]
> > 我在睿站发的视频不是有一个C++的吗
> 
> 啊 我不知道 整一个我瞅瞅

看看仓库里的`helang.cpp`
