### ISSUE TITLE
你们这个是什么项目啊，啊！

### ISSUE THREAD

**Issue by SekiBetu** [kifuan/helang#143]
不蹭不会写项目是吧？金无足赤人无完人，谁又是十全十美的？人就是有缺点才显得可贵，没缺点那就是神了，何同学有错就改，敢于面对自己的错误，多少up弄错了都是嘴硬不承认的？你们呢，你们写代码没弄错过吗，你敢说你们一直都是对的吗？真不知道现在风气怎么了，github怎么不把你们这些人封了，靠你们阴阳怪气科技能进步吗？而且从做视频的角度来说，何同学的视频趣味性都很充足，能让人看的津津有味，你的视频呢？枯燥乏味，什么亮点都没有，无聊的要死。你的视频很下头，但何同学的视频就很下肠，奉劝你们这些人好自为之，不要因为嫉妒蒙蔽了双眼，毁了未来的乔布斯！😡😡😡

**Comment by kifuan** [comment]
![(MHF} 01G`6`N}H(UE N6YS](https://user-images.githubusercontent.com/61240774/185351618-3dccd23b-093c-49a2-9165-5fca62b1a88f.jpg)

**Comment by MCredbear** [comment]
我趣，什么高强度互动

**Comment by Cyl18** [comment]
查重率100%🤣

**Comment by Redns** [comment]
这是友军还是水军😂，算了直接刀了🔪

**Comment by kifuan** [comment]
去discussions
