### ISSUE TITLE
爱❤来自Cyber Typescript，添加对HeScript/HypeScript/Hython/H++的支持

### ISSUE THREAD

**Issue by FurryR** [kifuan/helang#159]
请看以下代码：
```c
void powerCon(u8 whichKey, u8 Force) //1~68：调整任意对应按键力度 0：调整所有按键的力度
{
    if (whichKey)
        forceCon[whichKey - 1] = Force;
    else
        for (u8 i = 0; i < 68; i++)
            forceCon[i] = Force;
    Serial5.write(0xfe);
    Serial5.write(forceCon, 68);
}
```
由于`Serial5.write`涉及到了硬件操作，所以我们认为 **Saint He** 的思想是“贴近硬件”。
Typescript 语法优化版 [helang2](https://github.com/FurryR/helang2) 为此而生。
鉴定为初步符合 **Saint He** 贴近硬件的思想（直接操作寄存器）。
并且我们还加入了代码中的`if`语句，非常方便。
缺点：我懒得写`for`，于是我写了个`while`来代替。

**Comment by kifuan** [comment]
坏的实现，脱离HeLang！你这是HeAssembly！不够高科技！

**Comment by FurryR** [comment]
> 坏的实现，脱离HeLang！你这是HeAssembly！不够高科技！

正确的也是错误的
正确：这确实是HeAssembly
错误：仍然能够流畅使用5G，语法逆天，性能提高，图灵完备，给外星人看的
HeAssembly怎么会有条件控制语句呢？怎么会是呢？
