### ISSUE TITLE
德不配位，必有殃灾；才不堪任，必受其累。

### ISSUE THREAD

**Issue by qiannianshishui** [kifuan/helang#167]
露馅了吧!

黑子差不多得了，何同学是赛博天才5G唯一受益人名言“不觉得很酷吗”的发明者库克指定国区唯一乔布斯转世灵童曾做出苹果没有做成的高科技桌、开灯机器人等，一个视频使一家公司增值6个亿…黑子们尽管酸吧，将来他造出可控何聚变打你们的脸

(慕名而来)

**Comment by kifuan** [comment]
去discussions
