### ISSUE TITLE
关注这些宝藏UP主谢谢喵！

### ISSUE THREAD

**Issue by SakuraPuare** [kifuan/helang#170]
关注老师好我叫何同学谢谢喵！
关注LexBurner谢谢喵！
关注机智的党妹谢谢喵！
关注槐安遗梦谢谢喵！
关注点滴君谢谢喵！
关注郝给力谢谢喵！
关注波桑吃遍世界谢谢喵！
关注吃素的狮子谢谢喵！
关注拂菻坊谢谢喵！
关注吴织亚切大忽悠谢谢喵！
关注衣戈猜想谢谢喵！
关注白上吹雪Official谢谢喵！
关注回形针PaperClip谢谢喵！
关注信誓蛋蛋谢谢喵！
关注[欣小萌](https://space.bilibili.com/8366990/)谢谢喵！
关注[明前奶绿](https://space.bilibili.com/2132180406)谢谢喵！
![](https://github.com/SakuraPuare/Bilibili-Emoji-Downloader/raw/main/download/%E6%B4%9B%E5%A4%A9%E4%BE%9D8th%E7%94%9F%E6%97%A5%E7%BA%AA%E5%BF%B5/8-%E6%B4%9B%E5%A4%A9%E4%BE%9D_%E8%80%B6.png)

**Comment by SakuraPuare** [comment]
欢迎补充，不能让这些宝藏UP被我们大众忽略捏！![](https://github.com/SakuraPuare/Bilibili-Emoji-Downloader/raw/main/download/%E5%B0%8F%E9%BB%84%E8%84%B8/22-%E7%BB%99%E5%BF%83%E5%BF%83.png)

**Comment by kifuan** [comment]
还有[摸鱼摸摸鱼鱼](https://b23.tv/9XQ5Ccw)，也是喵。

**Comment by SakuraPuare** [comment]
> 还有[摸鱼摸摸鱼鱼](https://b23.tv/9XQ5Ccw)，也是喵。

早就关注了捏![](https://github.com/SakuraPuare/Bilibili-Emoji-Downloader/raw/main/download/%E5%B0%8F%E9%BB%84%E8%84%B8/25-%E5%96%9C%E6%AC%A2.png)

**Comment by qwqawawow** [comment]
请问白上吹雪和衣戈猜想有什么争议

**Comment by kifuan** [comment]
> 请问白上吹雪和衣戈猜想有什么争议

白上吹雪是HOLOLIVE的

衣戈猜想是二舅

**Comment by qwqawawow** [comment]
> > 请问白上吹雪和衣戈猜想有什么争议
> 
> 白上吹雪是HOLOLIVE的
> 
> 衣戈猜想是二舅

感谢

**Comment by Vucius** [comment]
感觉衣戈猜想还好啊，歌颂苦难的是狗官 不是他

**Comment by SakuraPuare** [comment]
> 感觉衣戈猜想还好啊，歌颂苦难的是狗官 不是他

视频被曝造假

**Comment by Vucius** [comment]
没有明前奶绿我不是很认可

**Comment by Vucius** [comment]
U1S1 欣小萌也值得关注

**Comment by SakuraPuare** [comment]
关注[欣小萌](https://space.bilibili.com/8366990/)谢谢喵！
关注[明前奶绿](https://space.bilibili.com/2132180406)谢谢喵！
![](https://github.com/SakuraPuare/Bilibili-Emoji-Downloader/raw/main/download/%E8%9B%86%E9%9F%B3%E5%A8%98/0-%E8%9B%86%E9%9F%B3%E5%A8%98_%E5%8D%96%E8%90%8C.png)

**Comment by kifuan** [comment]
去discussions
