### ISSUE TITLE
刚来

### ISSUE THREAD

**Issue by SAFEluren** [kifuan/helang#18]
请问米哈游就是用的HeLang做的原神吗？撅区零也是吗？

**Comment by kifuan** [comment]
是这样的，米哈游使用 helang 开发的 Henity 3D 开发一系列🔥🍗游戏

**Comment by CyberTNT** [comment]
哦天哪，这真的太酷了，满足我对米何游的一切幻想

**Comment by kifuan** [comment]
去discussions
