### ISSUE TITLE
你的素养很差

### ISSUE THREAD

**Issue by VirtualOilCake** [kifuan/helang#180]
你的素养很差，我现在每天玩原神都能赚150原石，每个月差不多5000原石的收入，也就是现实生活中每个月5000美元的收入水平，换算过来最少也30000人民币，虽然我只有14岁，但是已经超越了中国绝大多数人(包括你)的水平，这便是原神给我的骄傲的资本。这恰好说明了原神这个IP在线下使玩家体现出来的团结和凝聚力，以及非比寻常的脑洞，这种氛围在如今已经变质的漫展上是难能可贵的，这也造就了原神和玩家间互帮互助的局面，原神负责输出优质内容，玩家自发线下宣传和构思创意脑洞整活，如此良好的游戏发展生态可以说让其他厂商艳羡不已。反观腾讯的英雄联盟和王者荣耀，漫展也有许多人物，但是都难成气候，各自为营，更没有COS成水晶和精粹的脑洞，无论是游戏本身，还是玩家之间看一眼就知道原来你也玩原神的默契而非排位对喷，原神的成功和社区氛围都是让腾讯游戏难以望其项背的。一个不玩原神的人，有两种可能性。一种是没有能力玩原神。因为买不起高配的手机和抽不起卡等各种自身因素，他的人生都是失败的，第二种可能：有能力却不玩原神的人，在有能力而没有玩原神的想法时，那么这个人的思想境界便低到了一个令人发指的程度。一个有能力的人不付出行动来证明自己，只能证明此人行为素质修养之低下。是灰暗的，是不被真正的上流社会认可的。

**Comment by FurryR** [comment]
我去，原批！

**Comment by shshbb** [comment]
上次在公交车爱心座上玩原神，突然听到有人叫我原批，因为我是c语言大佬，所以我直接用程序黑了他的手机，他发现他手机被黑后气急败坏，顺手拿起一根20cm粗的钢管打我，然后我把钢管折断了，把他打得青一块紫一块的，让他住了好几天院，后来他出院了，给我赔礼道歉，请我给了杯白水，我一喝，好家伙，原来是硫酸，那钻心的疼让我一生难忘，然后我看到前面有一团红色，以为是鞭炮，准备吓一吓他，好家伙，原来是核弹，还好我和他都是体育生，跑得快，腿脚还利落，只是手被炸断了，在医院，医生测量了下我的体温，好家伙一百多度，本来是不疼的，结果庸医误诊说修养就好了，然后我拖着断手过了一周，疼得受不了了，才去复诊，打了仨月石膏。。。然而我现在还躺在病床上，令人感叹

**Comment by Yamilemon** [comment]
你说的对 但是《电子烟传奇》是由丁真珍珠自主研发的一款全新开放世界冒险游戏。游戏发生在一个被称作「 理塘」的幻想世界，在这里被神选中的人将被授予「电子烟」，引导尼古丁之力。你将扮演一位名为「芙蓉王Y」的神秘角色，在自由的旅行中邂逅性格各异、能力独特的动物朋友们，和它们一起击败强敌，找回不存在的亲人同——时，逐步发掘「理塘」的真相。

**Comment by FurryR** [comment]
抽象的捏

**Comment by kifuan** [comment]
去discussions
