### ISSUE TITLE
粘连科技降临到本仓库喵

### ISSUE THREAD

**Issue by kifuan** [kifuan/helang#185]
伟大的 **Cyber Spaces** 必将完成它的历史责任与使命！

**Comment by kifuan** [comment]
[fa03841](https://github.com/kifuan/helang/commit/fa03841cfc6c4578bfa24310dfbdce29a3350f2e)

**Comment by FurryR** [comment]
逆天

**Comment by shaokeyibb** [comment]
粘连科技我好爱你啊粘连科技🥵🥵🥵🥵

**Comment by Erica-Iris** [comment]
🥵🥵🥵🥵

**Comment by Vucius** [comment]
纯路人 能不能简单科普下粘连科技

**Comment by kifuan** [comment]
> 纯路人 能不能简单科普下粘连科技

是我跌

**Comment by shaokeyibb** [comment]
> 纯路人 能不能简单科普下粘连科技

你说的对，但是《粘连科技》是由​何世​杰自主研发的一款全新开放初生游戏。游戏发生在一个被称作「北京邮电大学」的幻想世界，在这里，被凯尔希选中的人将被授予「荣耀王者」，导引三相之力。你将扮演一位名为「电棍」的神秘角色，在自由的旅行中遇见性格各异、能力独特的梗小鬼们，和他们一起击败顶针，找回失散的华为Matebook——同时，逐步发掘「原神」的真相。​
