### ISSUE TITLE
什么时候出版相关书籍？

### ISSUE THREAD

**Issue by math-calculus** [kifuan/helang#197]
什么时候出版？

![页面 1 (1)](https://user-images.githubusercontent.com/69346913/185549416-68828895-763e-4521-b1f9-d53df014ff30.png)

**Comment by kifuan** [comment]
等到赛博108年就可以了

**Comment by rinne1998** [comment]
666

**Comment by dhxdltx** [comment]
![XLZZ8TK W4 4PR{7LO51FO](https://user-images.githubusercontent.com/100516349/185557660-ea28b9f2-719d-4f3d-b218-5f6ce6dba5d2.jpg)

**Comment by kifuan** [comment]
去discussions
