### ISSUE TITLE
已经构建出HeOS了，十分的好用

### ISSUE THREAD

**Issue by chingsky-liu** [kifuan/helang#205]
![Screenshot_20220819-143131~2](https://user-images.githubusercontent.com/80185263/185557486-b5bcb925-9552-411d-b04d-08b6270069d6.png)
世界第一的OS捏

**Comment by kifuan** [comment]
Hermony OS

**Comment by chingsky-liu** [comment]
> Hermony OS

说的很好，已经新建好组织了
https://github.com/Project-Hermony

**Comment by kifuan** [comment]
去discussions
