### ISSUE TITLE
不觉得很酷吗？作为一个理工男我觉得太酷了，很符合我对外来生活的想象。

### ISSUE THREAD

**Issue by dhxdltx** [kifuan/helang#207]
![XLZZ8TK W4 4PR{7LO51FO](https://user-images.githubusercontent.com/100516349/185558908-7c26c64a-efb4-48b6-993b-9537f749614c.jpg)

**Comment by kifuan** [comment]
👽是吧

**Comment by dhxdltx** [comment]
![9174D4A6D8627609D335F71AFC4CFE25](https://user-images.githubusercontent.com/100516349/185561422-70dd4561-ece1-44c2-80e8-c22e386fc26b.jpg)
![1658161818099](https://user-images.githubusercontent.com/100516349/185561426-01d72b4f-52a8-44ce-b0fb-1368f987d88d.png)

**Comment by DT9025A** [comment]
人家up也没做什么伤天害理的事情吧，就对他恶意这么大？
我看到好多人说他做的东西华而不实，水平不够专业，给我看笑了，假如专业水平是100分，人家好歹也做到了80分的水准，你们一群估计60分不到的在酸什么呢？
而且感觉跟职业黑子一样的，刚刚看到个贴，直接守着人家新视频发出，截图底下的评论。有必要吗？天天没事干就在网络上喷人，与其这么上心我劝你不如多打几份工赚钱。
而且他本来也没标榜自己做的东西就多顶尖了，很多人对数码领域基本都没什么了解的好吧，他就是一个普通的数码分享up，我们看他视频，也能简单了解一下这个领域的知识，观众和up都跟快乐，结果莫名其妙就被你们喷。
感觉逻辑就挺怪的，照你们这个说法不如把大学以下的老师都喷一遍吧，反正跟大学教授比起来他们水平肯定是不够高的。
还是那句话，不爱别伤害，你不喜欢他的视频，大不了就不看呗，B站也有拉黑功能。反正他的视频也有的是人看，不缺你们这点黑流量。天天生活不如意喷这喷那的，真的yue😡

**Comment by kifuan** [comment]
去discussions
