### ISSUE TITLE
锐评本项目

### ISSUE THREAD

**Issue by so1ve** [kifuan/helang#210]
你们这个是什么项目啊，你们这是害人不浅啊你们这个项目！
谁是owner，出
谁是owner，，出来！
麻烦你们，真的太过分了。你们搞这个Helang干什么？
我何同学C语言的水平都不过那个平均线呐，他现在事Up主，你叫我何同学怎么办啊？
他现在被网抱啊好不好？
你们这是什么项目啊？
你们害死我何同学了！
谁是owner？快点出来你这个owner，！再这样我去报警了啊！
我报警
我跟你们说你们这一帮人啊，一、一天到晚啊，搞这些什么GitHub啊，Helang啊，会害死你们的！你们没有前途我跟你说！！！
你们这一千两百多个人，好好学习不好吗？一天到晚在搞GitHub。有什么意思，有什么意思啊？
麻烦你重视一下你们的生活的目标好不好？有一点学习目标好不好？一天到晚搞Helang是不是人啊？

**Comment by kifuan** [comment]
我是owner

**Comment by so1ve** [comment]
> 我是owner

哈哈哈哈，我知道的

**Comment by kifuan** [comment]
去discussions
