### ISSUE TITLE
为什么没有日本语翻译

### ISSUE THREAD

**Issue by e5u** [kifuan/helang#214]
为什么没有日本语翻译
看不懂文档啊

**Comment by kifuan** [comment]
快请一个太军过来

**Comment by e5u** [comment]
可以是グーグル翻訳吗👀

Kifuan ***@***.***> 于 2022年8月19日周五 下午4:06写道：

**Comment by kifuan** [comment]
> B站私信东雪莲捏🥰

不行，不能让他看到我们对他在README结尾的恶意

**Comment by Vucius** [comment]
> 快请一个太军过来

你跌粘连科技不是会么

**Comment by e5u** [comment]
还真是

Vucius ***@***.***> 于 2022年8月19日周五 下午7:47写道：

**Comment by kifuan** [comment]
去discussions
