### ISSUE TITLE
你们怎么不遵守《何不扩散条约》

### ISSUE THREAD

**Issue by HeroChan0330** [kifuan/helang#225]
你们怎么不遵守《何不扩散条约》，把这么重要的机密发到美国人的平台上！

**Comment by kifuan** [comment]
哈人

**Comment by kifuan** [comment]
破案了，因为GITEE过不了审核

![image](https://user-images.githubusercontent.com/61240774/185591537-5ed6e2c6-8a18-46f1-a616-68f31eed8c18.png)

**Comment by kifuan** [comment]
去discussions
