### ISSUE TITLE
我没开5G😭我背叛了何圣😭

### ISSUE THREAD

**Issue by kifuan** [kifuan/helang#230]
![Snipaste_2022-08-19_18-02-44](https://user-images.githubusercontent.com/61240774/185595642-5cb375d2-dbe4-455b-91b5-bfdfd2955b29.jpg)

**Comment by e5u** [comment]
![Screenshot_20220819-190121_设置](https://user-images.githubusercontent.com/53000648/185604865-e7871eeb-79d6-434f-aa24-b78b7ccf95b4.png)
我手机没有5g，我背叛了何圣😭😭😭😭😭😭
