### ISSUE TITLE
英语翻译问题追踪

### ISSUE THREAD

**Issue by ZeroAurora** [kifuan/helang#232]
本 issue 用来持续追踪 https://github.com/kifuan/helang/blob/master/README-EN.MD 的各类问题，便于之后一次性修改提交。高考散装英语，还请宽容指正。
为什么要用英语翻译捏？不翻译还能和库克交流吗？
其实是翻译练手（确信）
## Won't Fix
- Spaces 的不可数问题 #216

预计维护到我开学为止。
cc @SherkeyXD

**Comment by kifuan** [comment]
都能有 `SpaceX`，我们 `SpaceS` 太正常了！

**Comment by kifuan** [comment]
加了一个二创，但是不着急，因为有很多改动，可以到时候统一写。

**Comment by ZeroAurora** [comment]
1.第一个 Summary 要改成 Overview
2. Litang 改成 Lithang

**Comment by kifuan** [comment]
蛤蛤，其实我写的那个概述是从英文的 Overview 翻译到中文的

**Comment by ZeroAurora** [comment]
> 蛤蛤，其实我写的那个概述是从英文的 Overview 翻译到中文的

然后我翻译就翻译成了头一个 Summary 尾一个 Summary，草

**Comment by kifuan** [comment]
没事，正常，这么抽象的长篇文章能翻译出来，太辛苦了

**Comment by kifuan** [comment]
76b77ea

虽然显示他改了，但好像什么都没改，不知道为什么

**Comment by kifuan** [comment]
[06912a5](https://github.com/kifuan/helang/commit/06912a5ef55250d6b03c8cab0bbee8ccec913052)

加了苹果的一些版权声明之类的东西，我看问题不太大，就再打回去。毕竟他也是辛苦写了
