### ISSUE TITLE
俄语翻译问题追踪

### ISSUE THREAD

**Issue by word0exe** [kifuan/helang#253]
本 issue 用来持续追踪 [README-RU.MD](https://github.com/kifuan/helang/blob/master/README-RU.MD) 的各类问题，便于之后一次性修改提交。原汁原味的俄语。

Этот issue используется для постоянного отслеживания проблем в [README-RU.MD](https://github.com/kifuan/helang/blob/master/README-RU.MD )это намного ускорит мою работу.

**Comment by word0exe** [comment]
我也开一个捏

**Comment by kifuan** [comment]
加了一个二创，但是不着急，因为有很多改动，可以到时候统一写。

**Comment by kifuan** [comment]
76b77ea

**Comment by word0exe** [comment]
https://github.com/kifuan/helang/commit/76b77ea4d7c0beef5b3ed9e7db32ed9ca2ca1346 https://github.com/kifuan/helang/commit/3da7f7de96f12529a0160241d378962f3d918a8c 已经解决 
详情->https://github.com/kifuan/helang/commit/03efccf52f1a44dd5fef659f5feaaa5e747fbe99

**Comment by kifuan** [comment]
[06912a5](https://github.com/kifuan/helang/commit/06912a5ef55250d6b03c8cab0bbee8ccec913052)

我看它加的和前面形式差不多，你要不再看看
