### ISSUE TITLE
一个建议，Publish Python Package

### ISSUE THREAD

**Issue by marc-shen** [kifuan/helang#257]
在action页面可以设置workflow，建议选择`Publish Python Package`，这样可以发表成为`conda/pip`包，便于安装使用。
<img width="773" alt="截屏2022-08-19 21 15 39" src="https://user-images.githubusercontent.com/59384269/185626517-bc165431-cb6c-4b56-a88f-5da4006f80ab.png">

**Comment by kifuan** [comment]
暂时不太考虑，因为最近功能还没齐全，不好发这种包。

**Comment by kifuan** [comment]
相当于还是 beta release

**Comment by ZeroAurora** [comment]
不投到 PyPI 上面其实不会有什么负面影响

**Comment by kifuan** [comment]
这只是个正经的整活项目，还是不要发 PyPI 了

**Comment by ZeroAurora** [comment]
> 这只是个正经的整活项目，还是不要发 PyPI 了

对，不过 GitHub 是自营仓库，不影响 PyPI
但也没什么必要，随意了（

**Comment by marc-shen** [comment]
有道理，毕竟是会产生影响的仓库
