### ISSUE TITLE
建议每个.he文件开头，必须声明1！5！🤗

### ISSUE THREAD

**Issue by PotatoCloud** [kifuan/helang#27]

**Comment by mack-w** [comment]
一把子支持了😋

**Comment by kifuan** [comment]
不行，那我一堆单元测试就跑不起来了！

![image](https://user-images.githubusercontent.com/61240774/185092902-2adcc6f9-b686-42d4-aaba-27e55f3c54da.png)

**Comment by Scirese** [comment]
> 不行，那我一堆单元测试就跑不起来了！
> 
> ![image](https://user-images.githubusercontent.com/61240774/185093010-55cf0fd3-5ed4-46b6-ba80-2d143387f37b.png)

错误的，不合理的😤
