### ISSUE TITLE
Can't clone

### ISSUE THREAD

**Issue by FrankHB** [kifuan/helang#271]
Since https://github.com/kifuan/helang/pull/267 is rejected, the `git clone` commands still just do not work without your SSH key. Is that expected?

**Comment by kifuan** [comment]
Can you give the error message git outputs?

**Comment by kifuan** [comment]
A possible reason is that you haven't configured your own ssh key yet.

**Comment by FurryR** [comment]
Please use `git clone https://github.com/kifuan/helang.git` instead.
note: This is not cool.

**Comment by kifuan** [comment]
Yes, not cool. Closed.

**Comment by FrankHB** [comment]
> Can you give the error message git outputs?

Cloning into 'helang'...
Connection closed by 192.30.255.112 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by FrankHB** [comment]
> A possible reason is that you haven't configured your own ssh key yet.

I have configured more than one SSH keys in GitHub in last decade.

It would be a stupid bug of GitHub if arbitrary SSH keys would work.

**Comment by kifuan** [comment]
那是你网络问题，我也经常这样。

**Comment by FurryR** [comment]
你要不`ssh git@github.com`试下能不能连上

**Comment by FrankHB** [comment]
> 那是你网络问题，我也经常这样。

Nope. I can clone other repos well, either `https`, `git`, or `ssh` *where I have the write access*.

It is a common sense that Git does not support SSH with anonymous read-only access, and GitHub is right here.

If you insist that should work, then publish your SSH private key here, and `git clone git@github.com:kifuan/helang.git` should be OK for everyone. That's how git+ssh supposed to work.

**Comment by kifuan** [comment]
我错了，我自裁

**Comment by kifuan** [comment]
已更正，感谢

**Comment by FrankHB** [comment]
Note that https://github.com/kifuan/helang/issues/267 is incomplete, so I've deleted that one. IIRC there are 2 problematic commands in *each* READMEs. So there should be at least 6 changes to fix.

**Comment by FrankHB** [comment]
> 已更正，感谢

Good. Confirmed to work.

(There seems some random delay of my comments here...)

**Comment by kifuan** [comment]
哈哈，我见识少了
之前都是自己一个人写东西，从来没注意过这些

谢谢喵

**Comment by kifuan** [comment]
哈哈，我见识少了
之前都是自己一个人写东西，从来没注意过这些

谢谢喵

**Comment by kifuan** [comment]
再次感谢，请原谅我的无知。

结合网上资料总结了一些写了一篇 blog。

**Comment by haimidaimaou** [comment]
😅 I CAN CLONE WITHOUT WRITE PRIVILEGE SO FUCK YOURSELF. @FrankHB 

Talk is cheap. Show me the code.

いわゆる規範が実践よりも高いと感じる場合は、自殺する必要があります。

**Comment by haimidaimaou** [comment]
😅 Ｉ　ＣＡＮ　ＣＬＯＮＥ　ＷＩＴＨＯＵＴ　ＷＲＩＴＥ　ＰＲＩＶＩＬＥＧＥ　ＳＯ　ＦＵＣＫ　ＹＯＵＲＳＥＬＦ．　@FrankHB

Ｔａｌｋ　ｉｓ　ｃｈｅａｐ．　Ｓｈｏｗ　ｍｅ　ｔｈｅ　ｃｏｄｅ．

ｲﾜﾕﾙｷﾊﾝｶﾞｼﾞｯｾﾝﾖﾘﾓﾀｶｲﾄｶﾝｼﾞﾙﾊﾞｱｲﾊ、ｼﾞｻﾂｽﾙﾋﾂﾖｳｶﾞｱﾘﾏｽ。

**Comment by FrankHB** [comment]
@haimidaimaou If that was true, you might better have something romantic with GitHub officially. And even this has been expected changed, it would not be true in arbitrary hosts, so this ain't ever relavant for a public Git repository not declared GitHub-only.

The code, whatever, has been shown for hours. How are you copy and pasting?

ﾃﾞｷﾅｶｯﾀｺﾄｶﾞﾃﾞｷﾀﾘｰ♪

**Comment by Akarinnnnn** [comment]
不应该啊，你的ssh公钥都过期了？

**Comment by kifuan** [comment]
不对啊， 我能用ssh克隆一个新仓库啊

**Comment by kifuan** [comment]
![image](https://user-images.githubusercontent.com/61240774/185843603-735b07be-1d1a-47ae-9597-36d8f94d6f89.png)

刚才试了一个仓库，我绝对没有写权限

**Comment by kifuan** [comment]
实践是检验真理的唯一标准。

**Comment by Akarinnnnn** [comment]
我是说帝球（ @FrankHB）

**Comment by kifuan** [comment]
> Cloning into 'helang'... Connection closed by 192.30.255.112 port 22 fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

还是你网络问题，我一开始也不能正常克隆，报错和你一样

**Comment by Akarinnnnn** [comment]
最好不要公开SSH和GPG私钥。如果不慎公开，建议尽快吊销。

**Comment by kifuan** [comment]
算了，无所谓，关了吧
