### ISSUE TITLE
About C--

### ISSUE THREAD

**Issue by FrankHB** [kifuan/helang#272]
> Nowadays in the 21st century, `Helang`,`Jvav` and `C--` have become the three irreplaceable programming languages.

It is somewhat curious that how these languages are placed together. Please clarify whether there is any officially approved endorsement of [C--](https://en.wikipedia.org/wiki/C--), as such information is also not available in [the official site](https://www.cs.tufts.edu/~nr/c--/index.html) thereof.

**Comment by kifuan** [comment]
Because `C--` is released in the year 108 of Cyber.

**Comment by haimidaimaou** [comment]
😅 NOBODY CARES ABOUT IT. GO FUCK YOURSELF.
