### ISSUE TITLE
为什么我们不能用HeLang实现开灯呢？

### ISSUE THREAD

**Issue by EvolvedGhost** [kifuan/helang#29]
かっこいいと思いませんか?理系の男性として、私はこれはとてもクールだと感じて、とても私の未来の生活の想像に符合して、科学技術といくつかの興味を持って​😎

**Comment by kifuan** [comment]
好功能，记下来了

**Comment by kifuan** [comment]
等我解一道圆锥曲线行吗😭

**Comment by Subway4M** [comment]
大佐的母语当上手：）

**Comment by EvolvedGhost** [comment]
> 大佐的母语当上手：）

对于一个理工男来说，这太酷了，不是吗

**Comment by CiroLong** [comment]
这太酷了，很符合我对理工男的浪漫想象

**Comment by Threegr3** [comment]
这太酷了，很符合我对理工男的浪漫想象

**Comment by Lstmxx** [comment]
cool japan

**Comment by Legendary-Zeraora** [comment]
这下看懂了

**Comment by ZeroAurora** [comment]
可以接入个网络请求的库，然后和智能家居框架联动。国内闭源的不清楚，开源的解决方案 openHAB 或者 Home Assistant 肯定是有 API 的

**Comment by FurryR** [comment]
> かっこいいと思いませんか?理系の男性として、私はこれはとてもクールだと感じて、とても私の未来の生活の想像に符合して、科学技術といくつかの興味を持って​**います**😎

龙鸣日语，但是指正

**Comment by kifuan** [comment]
看看置顶 Discussion 喵，看看置顶 Discussion 谢谢喵，有QQ群喵。
