### ISSUE TITLE
Feature Request: 希望来一套C++实现

### ISSUE THREAD

**Issue by MarkShawn2020** [kifuan/helang#32]

**Comment by kifuan** [comment]
不喜欢C++！
![image](https://user-images.githubusercontent.com/61240774/185092419-2a7d1638-407e-4af9-b08b-11ead97ac419.png)

**Comment by Grey0520** [comment]
> 

俺也一样

**Comment by Grey0520** [comment]
> 不喜欢C++！ ![image](https://user-images.githubusercontent.com/61240774/185092419-2a7d1638-407e-4af9-b08b-11ead97ac419.png)
俺也一样

**Comment by kifuan** [comment]
> It really is a crap language.
> 
> ---- Linus Benedict Torvalds
