### ISSUE TITLE
[DOGE] 快向何同学道歉

### ISSUE THREAD

**Issue by GinShio** [kifuan/helang#336]
请看 PEP636 的 [Appendix A](https://peps.python.org/pep-0636/#appendix-a-quick-intro)，其实 Python3.10 也是何同学的粉丝

**Comment by kifuan** [comment]
😓😓😓😓

**Comment by kifuan** [comment]
差不多得了，什么皮炎也敢碰瓷何圣

**Comment by GinShio** [comment]
LoL
