### ISSUE TITLE
所以是数一数二的新世代语言👍

### ISSUE THREAD

**Issue by justausernameforgithub** [kifuan/helang#38]
不觉得这很酷吗，作为一名8u我觉得这太酷了，很符合我对弄虚作假的科技区up的想象

**Comment by yu-steven** [comment]
数一数二的
![535E1F00-0E66-423C-AC9C-6FC59D8FD4D2](https://user-images.githubusercontent.com/78414278/185108507-511b2041-7136-41bd-8e39-facb7cc77388.jpeg)

**Comment by kifuan** [comment]
去discussions

**Comment by yu-steven** [comment]
好耶，开discussions咯
