### ISSUE TITLE
还不如坤语言

### ISSUE THREAD

**Issue by MoeX1n** [kifuan/helang#54]
来个坤坤不好吗？
![QQ图片20220817200730](https://user-images.githubusercontent.com/90125402/185114574-23809930-f575-4a4c-888a-f4a9cd89db03.jpg)

**Comment by kifuan** [comment]
他配高科技吗？

![image](https://user-images.githubusercontent.com/61240774/185115098-a050ee22-22ed-4fbc-97c9-c55505c50775.png)
