### ISSUE TITLE
艹，我是真的没有想到这地方也能玩抽象，另外仓库主人成分太复杂了

### ISSUE THREAD

**Issue by Sh1tWu** [kifuan/helang#68]

**Comment by kifuan** [comment]
![LYWH2}GFSYG340JOOST`5FF](https://user-images.githubusercontent.com/61240774/185157068-98aa5a5c-8482-4a2b-bcca-a9e25eba5bed.jpg)

**Comment by kifuan** [comment]
一点也不抽象喵
