### ISSUE TITLE
[Question] Refactoring My Existing Rust projects to HeLang

### ISSUE THREAD

**Issue by HonmaMeikodesu** [kifuan/helang#70]
Type: Question

Hi! I am fresh to HeLang and currently I am working on refactoring all my Rust projects to HeLang, and I wonder if there would be a LTS release of HeLang available in the future? BTW I found Rust a piece of shit after diving deep into the splendid design of HeLang and I can't wait to see more features supposed shiped by it, Appreciate your dedicated work to HeLang, love from LiTang!

IDE: LTCode
OS version: Hemony OS

**Comment by syrinka** [comment]
Greeting, throw away your poor rust and embrace the marvelous HeLang new world, lol.

**Comment by kifuan** [comment]
Thanks a lot for your love for HeLang! As more and more people discover this repository, I could ensure that HeLang will be the language for future!
