### ISSUE TITLE
怎么不支持宽字符？怎么不支持宽字符？

### ISSUE THREAD

**Issue by FurryR** [kifuan/helang#76]
怎么没有u8m4(u8 multiply 4)😡😡😡不能在多平台上打印立本的Hello World😡😡😡不是很支持

**Comment by kifuan** [comment]
😠你来提PR

**Comment by mrcaidev** [comment]
别急 `sprint 12371 | 12435 | 12395 | 12385 | 12399 | 19990 | 30028;`

**Comment by kifuan** [comment]
这不是能跑吗😠

**Comment by kifuan** [comment]
**Saint He** 的 `u8` 支持无穷大😠
