### ISSUE TITLE
[Bug] My HUAWEI laptop crashed when running HeLang

### ISSUE THREAD

**Issue by mrcaidev** [kifuan/helang#77]
- [x] I have read the documentation
- [x] There is no duplicate issue

## Bug Description

I changed `great.he` to this:
```
sprint 65 | 109 | 101 | 114 | 105 | 99 | 97;
```

And when I run `python main.py`, my HUAWEI laptop suddenly crashed and I had to reboot my machine. Is it something with the code or the language itself?

## Steps To Reproduce

```
echo "sprint 65 | 109 | 101 | 114 | 105 | 99 | 97;" > great.he
python main.py
```

## Environment

OS: Deepin
IDE: LTCode
Laptop: HUAWEI

**Comment by kifuan** [comment]
What a terrible bug!

However, it works on my Harmony OS, and it prints "China".

I have no idea what causes this bug.

**Comment by FurryR** [comment]
爱❤️来自亚美利加

**Comment by TomHedwig** [comment]
恨😡来自瓷器

**Comment by mrcaidev** [comment]
Fixed by changing my Chrome browser to 2345 browser👍
