### ISSUE TITLE
乐死了，等我明天起来以每分钟10甚至9个字符的速度弄个初生二创

### ISSUE THREAD

**Issue by FurryR** [kifuan/helang#79]
哈姆，哈姆，哈姆，哈姆的哈的贝哈姆哈姆的的哈贝贝，哈姆的哈的贝哈姆哈姆的哈贝贝，哈姆，哈姆，古莫德那德米列洛姆，古莫德那德米列洛玛，古莫德那德米列洛玛，阿珂么德哈马迪，阿珂么德哈马迪，哈姆，哈姆，哈姆，哈姆的哈的贝哈姆哈姆的的哈贝贝，哈姆的哈的贝哈姆哈姆的哈贝贝，哈姆，哈姆，古莫德那德米列洛姆，古莫德那德米列洛玛，古莫德那德米列洛玛，阿珂么德哈马迪，阿珂么德哈马迪哈姆，哈姆，哈姆，哈姆的哈的贝哈姆哈姆的的哈贝贝，哈姆的哈的贝哈姆哈姆的哈贝贝，哈姆，哈姆，古莫德那德米列洛姆，古莫德那德米列洛玛，古莫德那德米列洛玛，阿珂么德哈马迪，阿珂么德哈马迪，哈姆，哈姆，哈姆，哈姆的哈的贝哈姆哈姆的的哈贝贝，哈姆的哈的贝哈姆哈姆的哈贝贝，哈姆，哈姆，古莫德那德米列洛姆，古莫德那德米列洛玛，古莫德那德米列洛玛，阿珂么德哈马迪，阿珂么德哈马迪哈姆，哈姆，哈姆，哈姆的哈的贝哈姆哈姆的的哈贝贝，哈姆的哈的贝哈姆哈姆的哈贝贝，哈姆，哈姆，古莫德那德米列洛姆，古莫德那德米列洛玛，古莫德那德米列洛玛，阿珂么德哈马迪，阿珂么德哈马迪，哈姆，哈姆，哈姆，哈姆的哈的贝哈姆哈姆的的哈贝贝，哈姆的哈的贝哈姆哈姆的哈贝贝，哈姆，哈姆，古莫德那德米列洛姆，古莫德那德米列洛玛，古莫德那德米列洛玛，阿珂么德哈马迪，阿珂么德哈马迪

**Comment by TomHedwig** [comment]
怎么这里也有homo啊(恼)

**Comment by DT9025A** [comment]
homo特有的9大于10

**Comment by KaoruAsajitsu** [comment]
每次看到有人说十甚至九是homo语的时候都一阵恶寒

**Comment by FurryR** [comment]
小鬼退散，创谢，，，

**Comment by HenryVarro666** [comment]
你真是一个一个一个一个一个。。。哼哼啊啊啊啊啊啊啊啊啊~~~~~

**Comment by FurryR** [comment]
> 你真是一个一个一个一个一个。。。哼哼啊啊啊啊啊啊啊啊啊~~~~~

我去，是玩梗大手子
