### ISSUE TITLE
现在 Helang 登陆 ArchLinux 啦 2333

### ISSUE THREAD

**Issue by BenderBlog** [kifuan/helang#81]
玩票性质，所以所有的东西都打在了 /opt 下面，随便玩玩就好。
想用的话请去 https://github.com/BenderBlog/Practise-Programs/tree/main/Helang-PKGBUILD 看看，感觉没必要上传到 AUR 了。

对于某些人来说，很符合对 Linux 的想象，吃饱了没事干(滑稽)

**Comment by kifuan** [comment]
Another great achievement.

**Comment by kifuan** [comment]
把你加到二创列表了

[3507047](https://github.com/kifuan/helang/commit/350704785930cc81f8645cc85a8901b77358a57f)
