### ISSUE TITLE
何言何语征集！

### ISSUE THREAD

**Issue by ZeroAurora** [kifuan/helang#83]
在程序结束时随机打印一句河言河语，您意下如何🤔

**Comment by kifuan** [comment]
好，你能帮我找找吗，足够多我就加进去。

**Comment by kifuan** [comment]
> 好，你能帮我找找吗，足够多我就加进去。

什么懒狗😓

**Comment by ZeroAurora** [comment]
> 好，你能帮我找找吗，足够多我就加进去。

不能捏
反转了，在座的都是懒狗捏😋

**Comment by kifuan** [comment]
睡了，明天起来找

**Comment by RLLDLBF** [comment]
《在回去的路上，我陷入了对人生的大思考》

**Comment by nukemiko** [comment]
《都什么年代了还在用传统代码托管平台》

**Comment by LebranceBW** [comment]
《你在写何语言的时候，丁真在下棋》

**Comment by mrcaidev** [comment]
> > 好，你能帮我找找吗，足够多我就加进去。
> 
> 什么懒狗sweat

精神分裂是吧

**Comment by Weiwong1996** [comment]
《如果何同学需要鼓励的话，我会对他说：我测你码》

**Comment by zer0fire** [comment]
《历经 xx 天，我做了一个 xxx》函数模板

**Comment by dhxdltx** [comment]
做正确的代码，不应该很难吗？

**Comment by Yamilemon** [comment]
芝士雪豹 芝士猞猁 芝士 我测你们码

**Comment by Waker123** [comment]
能不能加个Zood啊，1！5！，不觉得这是一件很酷的事情吗🕶

**Comment by willshion** [comment]
科技 丁真

**Comment by Xabws** [comment]
> 为什么不是 she-lang ？

好拳法，哈哈哈哈
