### ISSUE TITLE
LOGO征集（以点赞数投票，右上角）

### ISSUE THREAD

**Issue by Tinhone** [kifuan/helang#87]
![test2](https://user-images.githubusercontent.com/81268244/185203365-37d5c679-1fc5-44a4-b77f-f60d1a6b7fb8.png)

233

**Comment by kifuan** [comment]
哈哈，我明天征集一天

**Comment by Tinhone** [comment]
正确的👍

**Comment by Tinhone** [comment]
RIGHT👍

**Comment by BlackTitle** [comment]
![cyberdingzhen-LOGO](https://user-images.githubusercontent.com/79453075/185233060-ba636012-27ca-4efb-83f7-7b87d4fd6dc3.png)
![cyberdingzhen](https://user-images.githubusercontent.com/79453075/185233092-b44041e2-5666-4c29-b27f-50a9ebd7f7c7.png)
主要就体验一个赛博丁真人上人XD  纯纯乐子LOGO  看个笑话吧

**Comment by BlackTitle** [comment]
![cyberdingzhen](https://user-images.githubusercontent.com/79453075/185233294-60a8ad38-6988-4140-ba32-75d204146c40.png)
![cyberdingzhen-LOGO](https://user-images.githubusercontent.com/79453075/185233304-4e01a41f-d2c4-4f6a-93cd-6ed6642e5acf.png)
主要就体现一个赛博丁真人上人XD 纯纯乐子LOGO 看个笑话吧

**Comment by shaokeyibb** [comment]
> ![cyberdingzhen](https://user-images.githubusercontent.com/79453075/185233294-60a8ad38-6988-4140-ba32-75d204146c40.png) ![cyberdingzhen-LOGO](https://user-images.githubusercontent.com/79453075/185233304-4e01a41f-d2c4-4f6a-93cd-6ed6642e5acf.png) 主要就体现一个赛博丁真人上人XD 纯纯乐子LOGO 看个笑话吧

太正式了，正式到我以为这是个正经项目了捏😋

**Comment by kifuan** [comment]
> > ![cyberdingzhen](https://user-images.githubusercontent.com/79453075/185233294-60a8ad38-6988-4140-ba32-75d204146c40.png) ![cyberdingzhen-LOGO](https://user-images.githubusercontent.com/79453075/185233304-4e01a41f-d2c4-4f6a-93cd-6ed6642e5acf.png) 主要就体现一个赛博丁真人上人XD 纯纯乐子LOGO 看个笑话吧
> 
> 太正式了，正式到我以为这是个正经项目了捏😋

这什么时候不是正经项目😠

**Comment by math-calculus** [comment]
![HelangLogo](https://user-images.githubusercontent.com/69346913/185286840-cbfdefbf-7317-40a7-b83b-f2c5594f09a5.png)

**Comment by LiuHsiao** [comment]
![HELANG](https://user-images.githubusercontent.com/111480192/185293562-aa2869ad-ea9e-41d3-9f0e-565be2af955d.png)

**Comment by xieyuheng** [comment]
LOGO 应该是「一个盒子，将要打开的样子。」
懂吗？

**Comment by royalknight56** [comment]
![未标题-1](https://user-images.githubusercontent.com/34654733/185308530-d6d0d1e8-b8e1-42ae-be08-4e4501f6d8b3.png)
乔布斯钦点转世灵童，苹果子公司，锤子孙公司创始人。

**Comment by SAFEluren** [comment]
![YQYJ03YCVYUPNBKE{QMYRYB](https://user-images.githubusercontent.com/79032826/185354991-0cc688b8-84bc-4d86-93f1-d76efe7456d2.png)
竞标

**Comment by EvolvedGhost** [comment]
![hl](https://user-images.githubusercontent.com/92856393/185355177-22cfe003-c0f7-403a-90b6-47631835fe3d.svg)
基于OpenMoji(CC-BY-SA-4.0)和免费可商用字体GOTA做的，应该没版权问题

**Comment by lovemyFamilyFovever** [comment]
这个太搞了吧！笑死。

**Comment by kifuan** [comment]
点赞来投票喵，点赞投票谢谢喵

**Comment by forntarv** [comment]
![HELANG](https://user-images.githubusercontent.com/110398313/185411780-34dccf88-2d27-4377-834c-e1a051a0ec7d.png)
鉴于何同学是一名果粉因而整此烂活

**Comment by kifuan** [comment]
> ![hl](https://user-images.githubusercontent.com/92856393/185355177-22cfe003-c0f7-403a-90b6-47631835fe3d.svg) 基于OpenMoji(CC-BY-SA-4.0)和免费可商用字体GOTA做的，应该没版权问题

好！就你点赞最多！

**Comment by jukrb0x** [comment]
为什么logo上没有赛博电子烟
