### ISSUE TITLE
太抽象了，顺便能关注露早吗？

### ISSUE THREAD

**Issue by yzhe819** [kifuan/helang#92]
**群星在闪耀！露早在发光！** 🤤
![图片](https://user-images.githubusercontent.com/68207314/185263767-4c1e61a7-9448-4c70-b395-37a8c46a4903.png)

**Comment by kifuan** [comment]
管人痴差不多得了

**Comment by mrcaidev** [comment]
关注早神的人品味素质修养都很高

**Comment by SekiBetu** [comment]
关注米诺喵，关注学会炒作喵！

**Comment by kifuan** [comment]
去discussions
