### ISSUE TITLE
@老师好我叫何同学

### ISSUE THREAD

**Issue by Kento97** [kifuan/helang#94]

**Comment by kifuan** [comment]
他会上github吗😋🤣

**Comment by Kento97** [comment]
> 他会上github吗😋🤣

很好笑的话，来自契丹

**Comment by kifuan** [comment]
> > 他会上github吗😋🤣
> 
> 很好笑的话，来自契丹

英雄联盟，爱来自瓷器

**Comment by shaokeyibb** [comment]
就是你把皇军引过来的？😋

**Comment by DreamingCats** [comment]
> 他会上github吗😋🤣

《GitHub打不开》

**Comment by DRSalieri** [comment]
> > 他会上github吗😋🤣
> 
> 《GitHub打不开》

下一个视频就是《我花了108个小时登上了GITHUB...》

**Comment by kifuan** [comment]
去discussions
